//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.pgn.v1.cis.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "CisHackathonServiceService", targetNamespace = "http://www.pgn.com/v1/cis/wsdl", wsdlLocation = "wksp:/HackathonTempLibrary/wsdl/v1/CisHackathonServiceService.wsdl")
public class CisHackathonServiceService
    extends Service
{

    private final static URL CISHACKATHONSERVICESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = com.pgn.v1.cis.wsdl.CisHackathonServiceService.class.getResource("null");
            if (url == null) throw new MalformedURLException("null does not exist in the module.");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CISHACKATHONSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CisHackathonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CisHackathonServiceService() {
        super(CISHACKATHONSERVICESERVICE_WSDL_LOCATION, new QName("http://www.pgn.com/v1/cis/wsdl", "CisHackathonServiceService"));
    }

    /**
     * 
     * @return
     *     returns CisHackathonService
     */
    @WebEndpoint(name = "CisHackathonServicePort")
    public CisHackathonService getCisHackathonServicePort() {
        return (CisHackathonService)super.getPort(new QName("http://www.pgn.com/v1/cis/wsdl", "CisHackathonServicePort"), CisHackathonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CisHackathonService
     */
    @WebEndpoint(name = "CisHackathonServicePort")
    public CisHackathonService getCisHackathonServicePort(WebServiceFeature... features) {
        return (CisHackathonService)super.getPort(new QName("http://www.pgn.com/v1/cis/wsdl", "CisHackathonServicePort"), CisHackathonService.class, features);
    }

}
