//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.pgn.v1.cis.wsdl;

import javax.xml.ws.WebFault;
import com.pgn._2010._07.fault.xsd.ServiceFault;

@WebFault(name = "insertOneClickPaymentFault1_serviceFault", targetNamespace = "http://www.pgn.com/v1/cis/wsdl")
public class InsertOneClickPaymentServiceFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InsertOneClickPaymentServiceFaultMsg(String message, ServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public InsertOneClickPaymentServiceFaultMsg(String message, ServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.pgn._2010._07.fault.xsd.ServiceFault
     */
    public ServiceFault getFaultInfo() {
        return faultInfo;
    }

}
