//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.pgn.v1.cis.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlRootElement(name = "insertOneClickPayment", namespace = "http://www.pgn.com/v1/cis/wsdl")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "insertOneClickPayment", namespace = "http://www.pgn.com/v1/cis/wsdl", propOrder = {
    "customerCode",
    "premiseCode",
    "paymentAmount",
    "paymentDate"
})
public class InsertOneClickPayment {

    @XmlElement(name = "customerCode", namespace = "")
    private Integer customerCode;
    @XmlElement(name = "premiseCode", namespace = "")
    private String premiseCode;
    @XmlElement(name = "paymentAmount", namespace = "")
    private Float paymentAmount;
    @XmlElement(name = "paymentDate", namespace = "")
    private XMLGregorianCalendar paymentDate;

    /**
     * 
     * @return
     *     returns Integer
     */
    public Integer getCustomerCode() {
        return this.customerCode;
    }

    /**
     * 
     * @param customerCode
     *     the value for the customerCode property
     */
    public void setCustomerCode(Integer customerCode) {
        this.customerCode = customerCode;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getPremiseCode() {
        return this.premiseCode;
    }

    /**
     * 
     * @param premiseCode
     *     the value for the premiseCode property
     */
    public void setPremiseCode(String premiseCode) {
        this.premiseCode = premiseCode;
    }

    /**
     * 
     * @return
     *     returns Float
     */
    public Float getPaymentAmount() {
        return this.paymentAmount;
    }

    /**
     * 
     * @param paymentAmount
     *     the value for the paymentAmount property
     */
    public void setPaymentAmount(Float paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    /**
     * 
     * @return
     *     returns XMLGregorianCalendar
     */
    public XMLGregorianCalendar getPaymentDate() {
        return this.paymentDate;
    }

    /**
     * 
     * @param paymentDate
     *     the value for the paymentDate property
     */
    public void setPaymentDate(XMLGregorianCalendar paymentDate) {
        this.paymentDate = paymentDate;
    }

}
