//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.pgn.com/2010/07/common/xsd")
package com.pgn._2010._07.common.xsd;
