//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.pgn._2010._07.fault.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This fault should be thrown anytime an unhandled runtime error is encountered in an operation.
 * 
 * <p>Java class for ServiceFault complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceFault">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pgn.com/2010/07/fault/xsd}BaseFault">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceFault", namespace = "http://www.pgn.com/2010/07/fault/xsd")
public class ServiceFault
    extends BaseFault
{


}
